#nom de l'application
name: my-ci
# On déclenche le workflow sur tout push sur la branche courante
on: [push]
jobs:
  #nom du job
  build-deploy-docker:
    # environnement utilise
    runs-on: ubuntu-latest
    # les étapes
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/getting-started:latest
        #node-version: '14'
        #- run: npm install -g bats
        #- run: bats -v
