#nom de l'application
name: my-ci
# On déclenche le workflow sur tout push sur la branche courante
on: [push]
jobs:
  #nom du job
  build-deploy-docker:
    # environnement utilise
    runs-on: ubuntu-latest
    # les étapes
    steps:
      - uses: actions/checkout@v4
      steps: 
        -run: ls
      #- uses: actions/setup-node@v3
      #with:
        #node-version: '14'
        #- run: npm install -g bats
        #- run: bats -v
